default_language_version:
  python: python3.12
  
repos:
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.19
    hooks:
      - id: mdformat
        additional_dependencies:
          - "mdformat-mkdocs[recommended]"